### ISSUE TITLE
Failed to activate the jshint package

### ISSUE THREAD

**Issue by prrrnd** [sindresorhus/atom-jshint#145] opened 2015-11-03 07:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Failed to activate the jshint package

```
At element.addEventListener is not a function

TypeError: element.addEventListener is not a function
    at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
    at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
    at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
    at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
    at addReasons (/Users/centic/.atom/packages/jshint/index.js:169:32)
    at displayError (/Users/centic/.atom/packages/jshint/index.js:189:2)
    at /Users/centic/.atom/packages/jshint/index.js:196:24
    at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
    at displayErrors (/Users/centic/.atom/packages/jshint/index.js:196:4)
    at registerEvents (/Users/centic/.atom/packages/jshint/index.js:288:2)
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:145:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:289:33)
    at Object.activate (/Users/centic/.atom/packages/jshint/index.js:332:38)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
     -0:22.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "~/work",
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13
file-icons, v1.6.11
jshint, v1.8.3
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-js-yaml, v1.2.0
linter-jscs, v3.1.2
linter-jshint, v1.2.1
linter-ruby, v1.2.0
minimap, v4.16.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment] 2015-11-03 13:20
Duplicate of #143.

**Closed by ArtskydJ** 2015-11-03 13:20 UTC
