### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by alex-sobolev** [sindresorhus/atom-jshint#144] opened 2015-11-02 03:10 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\src\delegated-listener.js:36

TypeError: element.addEventListener is not a function
    at listen (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\src\delegated-listener.js:36:11)
    at [object Object].Tooltip.init (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip.js:83:28)
    at new Tooltip (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip.js:18:8)
    at TooltipManager.module.exports.TooltipManager.add (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip-manager.js:50:17)
    at addReasons (C:/Users/Alexander_Sobolev/.atom/packages/jshint/index.js:169:32)
    at displayError (C:/Users/Alexander_Sobolev/.atom/packages/jshint/index.js:189:2)
    at C:/Users/Alexander_Sobolev/.atom/packages/jshint/index.js:196:24
    at arrayEach (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\Alexander_Sobolev\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at displayErrors (C:/Users/Alexander_Sobolev/.atom/packages/jshint/index.js:196:4)
```

### Commands

```
     -3:11.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:54.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:54.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:52.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:49.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:42 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:42 snippets:expand (atom-text-editor.editor.is-focused)
     -2:42 editor:indent (atom-text-editor.editor.is-focused)
  4x -0:43.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.9.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:10.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:07.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
color-picker, v2.0.13
emmet, v2.3.13
jshint, v1.8.3
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by jmsherry** [comment] 2015-11-02 12:40
What is this?? I opened atom (on mac [el capitan] atom v. 1.1.0) this morning and suddenly:

<img width="510" alt="screen shot 2015-11-02 at 12 31 55" src="https://cloud.githubusercontent.com/assets/697341/10881813/dbc870d4-815d-11e5-992f-5680eacc0e91.png">

<img width="456" alt="screen shot 2015-11-02 at 12 33 37" src="https://cloud.githubusercontent.com/assets/697341/10881863/47d6ef62-815e-11e5-8cf8-b5729b0fd2ed.png">

Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.22.0
├── autocomplete-snippets@1.7.1
├── autoflow@0.26.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.78.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.185.0
├── fuzzy-finder@0.90.0
├── git-diff@0.56.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.55.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.48.0
├── language-clojure@0.18.0
├── language-coffee-script@0.42.0
├── language-csharp@0.11.0
├── language-css@0.34.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.39.0
├── language-html@0.42.0
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.96.0
├── language-json@0.17.0
├── language-less@0.28.2
├── language-make@0.19.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.0
├── language-perl@0.30.0
├── language-php@0.30.0
├── language-property-list@0.8.0
├── language-python@0.40.0
├── language-ruby@0.60.0
├── language-ruby-on-rails@0.23.0
├── language-sass@0.42.0
├── language-shellscript@0.19.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.33.0
├── language-yaml@0.24.0
├── line-ending-selector@0.2.0
├── link@0.31.0
├── markdown-preview@0.154.0
├── metrics@0.53.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.5
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.5
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.230.0
├── snippets@0.100.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.61.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.109.0
├── tabs@0.84.0
├── timecop@0.33.0
├── tree-view@0.190.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.38.0

/Users/jamessherry/.atom/packages (6)
├── atom-beautify@0.28.15
├── change-case@0.6.0
├── emmet@2.3.13
├── jshint@1.8.1
├── minimap@4.15.0
└── pigments@0.18.0

**Comment by xdumaine** [comment] 2015-11-02 13:56
Same here.

**Comment by atalargo** [comment] 2015-11-02 15:33
Same problem here with the version 1.8.3 of the plugin (atom 1.1.0, on MacOS X). 
I think i've the last version available, because no newer version available in update atom's window)

**Comment by Aurthes** [comment] 2015-11-02 17:45
Same here, please help.

**Comment by ArtskydJ** [comment] 2015-11-02 17:48
Duplicate of #143.

**Closed by ArtskydJ** 2015-11-02 17:48 UTC

**Comment by austinkelleher** [comment] 2015-11-03 15:58
+1

**Comment by amhed** [comment] 2015-11-03 16:51
Still getting the error after update as well

**Comment by ryedin** [comment] 2015-11-03 17:52
Issue is not fixed yet

**Comment by s-ogawa-mediba** [comment] 2015-11-04 07:23
i guess that this issue is not fiexed.

**Comment by ArtskydJ** [comment] 2015-11-04 13:34
This issue was closed because it was a duplicate. The issue is being tracked in #143.

**Comment by adrian273** [comment] 2015-11-04 21:18
cuando se arreglera es bug?

**Comment by ArtskydJ** [comment] 2015-11-04 21:47
@adrian273 Deshabilitar y volver a habilitar atom-jshint.
