### ISSUE TITLE
atom.workspaceView..oh god...I AM obsessive

### ISSUE THREAD

**Issue by qddegtya** [sindresorhus/atom-jshint#65] opened 2015-02-05 10:33 UTC
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.

**Comment by sindresorhus** [comment] 2015-02-06 16:05
Duplicate of #58. Please search the issue tracker before opening a ticket.

**Closed by sindresorhus** 2015-02-06 16:05 UTC
