### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by MatthewHerbst** [sindresorhus/atom-jshint#146] opened 2015-11-04 22:38 UTC
I keep getting this error. Just upgraded to newest version of Atom and atom-jshint. Editing some React code in a .jsx file.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/Users/mherbst/.atom/packages/jshint/index.js:186:30)
  at displayError (/Users/mherbst/.atom/packages/jshint/index.js:206:2)
  at /Users/mherbst/.atom/packages/jshint/index.js:214:10
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/Users/mherbst/.atom/packages/jshint/index.js:213:4)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -1:16 editor:newline (atom-text-editor.editor.is-focused)
     -1:14 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:04.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:35.9.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:31.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:11.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:07.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.11
jshint, v1.8.3
linter, v1.10.0
linter-cpplint, v1.0.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-javac, v1.3.0
linter-php, v1.0.5
linter-pylint, v1.0.3
linter-scalac, v1.1.0
linter-xmllint, v0.0.7
monokai, v0.18.0
pretty-json, v0.4.1
react, v0.12.10
set-syntax, v0.3.0
svn, v0.0.8

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment] 2015-11-04 22:55
Try disabling and re-enabling `atom-jshint`.

**Comment by ArtskydJ** [comment] 2015-11-04 22:55
Duplicate of #143.

**Closed by ArtskydJ** 2015-11-04 22:55 UTC

**Comment by MatthewHerbst** [comment] 2015-11-04 23:09
Problem seemed to go away by closing Atom and restarting from the command line (which I guess has the same effect as re-enabling `atom-jshint`?)
