### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by israel-viveros** [sindresorhus/atom-jshint#147] opened 2015-11-05 17:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/Users/joseviveros/.atom/packages/jshint/index.js:186:30)
  at displayError (/Users/joseviveros/.atom/packages/jshint/index.js:206:2)
  at /Users/joseviveros/.atom/packages/jshint/index.js:214:10
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/Users/joseviveros/.atom/packages/jshint/index.js:213:4)
  at lint (/Users/joseviveros/.atom/packages/jshint/index.js:293:2)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -1:00.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:00.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:00.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:44.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:41.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:40.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:40.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:34 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:34 editor:newline (atom-text-editor.editor.is-focused)
     -0:33.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:33.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "es6-javascript",
      "docblockr",
      "atom-alignment"
    ],
    "openEmptyEditorOnStart": false
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
emmet, v2.3.14
file-icons, v1.6.11
highlight-line, v0.11.0
jshint, v1.8.3
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment] 2015-11-05 17:08
Please disable `atom-jshint`, restart atom, and then enable `atom-jshint`.

**Comment by ArtskydJ** [comment] 2015-11-05 17:47
Duplicate of #143.

**Closed by ArtskydJ** 2015-11-05 17:47 UTC
