### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by syda** [sindresorhus/atom-jshint#67] opened 2015-02-09 13:35 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\syd\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
registerEvents (C:\Users\syd\.atom\packages\jshint\index.js:260:6)
```

**Comment by sindresorhus** [comment] 2015-02-09 13:51
Duplicate of #66 #65 #63 #58.

Please check the issue tracker before opening an issue.

**Closed by sindresorhus** 2015-02-09 13:51 UTC
