### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by mersocarlin** [sindresorhus/atom-jshint#149] opened 2015-11-11 21:20 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/Users/mersocarlin/.atom/packages/jshint/index.js:186:30)
  at displayError (/Users/mersocarlin/.atom/packages/jshint/index.js:206:2)
  at /Users/mersocarlin/.atom/packages/jshint/index.js:214:10
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/Users/mersocarlin/.atom/packages/jshint/index.js:213:4)
  at lint (/Users/mersocarlin/.atom/packages/jshint/index.js:293:2)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -1:09.6.0 grammar-selector:show (a.inline-block)
  2x -1:08.8.0 editor:split-selections-into-lines (a.inline-block)
     -1:05.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:55.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.6.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:42.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:19.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:14.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14 core:move-down (atom-text-editor.editor.is-focused)
     -0:12 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:05.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:02.8.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.17
atom-material-ui, v0.8.0
color-picker, v2.0.13
css-snippets, v0.9.0
file-icons, v1.6.11
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jshint, v1.8.3
language-babel, v2.3.1
language-javascript-jsx, v0.3.7
linter-jshint, v1.2.1
pretty-json, v0.4.1
react, v0.12.10
react-snippets, v0.2.0

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment] 2015-11-12 13:15
Please disable `atom-jshint`, restart atom, and re-enable `atom-jshint`.

**Comment by ArtskydJ** [comment] 2015-11-12 13:16
Duplicate of #143.

**Closed by ArtskydJ** 2015-11-12 13:16 UTC

**Comment by marclundgren** [comment] 2015-12-01 20:09
disabling, restarting atom and re-enabling didn't fix the problem for me. However, uninstalling, restarting, then re-installing did the trick.
