### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by donvercety** [sindresorhus/atom-jshint#66] opened 2015-02-06 14:34 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
updateStatusbar (/home/lubo/.atom/packages/jshint/index.js:86:11)
```

**Comment by sindresorhus** [comment] 2015-02-06 16:04
Duplicate of #58. Please search the issue tracker before opening a ticket.

**Closed by sindresorhus** 2015-02-06 16:04 UTC
