### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by silverskyvicto** [sindresorhus/atom-jshint#153] opened 2015-11-18 12:22 UTC
When I opened the atom, the following error has occurred.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at TextEditor.module.exports.TextEditor.onDidChangeScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:375:12)
    at registerEvents (/Users/ey/.atom/packages/jshint/index.js:301:32)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:312:21)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:306:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:387:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:449:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
     -9:49.4.0 mavensmate:open-project (button.btn.icon.enablement.icon-playback-play)
     -9:38.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:45 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:34.8.0 application:new-file (atom-pane.pane.active)
     -1:18.1.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "vim-mode",
      "japanese-wrap"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.6
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-html-preview, v0.1.13
auto-indent, v0.5.0
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.4
cargo-test-runner, v0.0.4
color-picker, v2.0.13
commonform, v0.1.1
docblockr, v0.7.3
file-icons, v1.6.11
gist-it, v0.8.0
git-grep, v0.9.0
git-log, v0.4.1
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
japanese-menu, v1.5.0
javascript-snippets, v1.0.0
jshint, v1.8.3
language-babel, v2.5.0
language-docker, v1.1.3
language-javascript-jsx, v0.3.7
language-plantuml, v0.1.1
language-rust, v0.4.5
language-salesforce, v0.6.0
line-jumper, v0.14.1
linter, v1.11.2
linter-javac, v1.3.0
linter-jscs, v3.2.0
linter-jsxhint, v0.1.2
linter-rust, v0.2.10
markdown-format, v2.5.1
markdown-preview-plus, v2.2.2
minimap, v4.16.0
node-debugger, v1.1.9
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-react-native-inspector, v0.0.0
nuclide-remote-projects, v0.0.32
pigments, v0.18.1
plantuml-viewer, v0.7.0
pretty-json, v0.4.1
preview-plus, v1.2.6
project-manager, v2.6.5
racer, v0.17.2
react, v0.12.10
react-snippets, v0.3.0
refactor, v0.6.0
regex-railroad-diagram, v0.10.4
rust-api-docs-helper, v0.5.1
show-ideographic-space, v1.0.1
trailing-spaces, v0.3.2
tree-view-git-projects, v0.5.0
wordcount, v2.4.1

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment] 2015-11-18 13:23
Duplicate of #151.

**Closed by ArtskydJ** 2015-11-18 13:23 UTC

**Comment by ArtskydJ** [comment] 2015-11-20 15:07
In #151, @jacarma had success uninstalling nuclide.
