### ISSUE TITLE
No error message from the current line

### ISSUE THREAD

**Issue by helloncanella** [sindresorhus/atom-jshint#131] opened 2015-10-15 17:11 UTC
When the error occurs, in the current line, the red strip appears but not the error message.

The message with the error is just found on the bottom of the page.

**Comment by sindresorhus** [comment] 2015-10-15 17:22
Duplicate of https://github.com/sindresorhus/atom-jshint/issues/121.

**Closed by sindresorhus** 2015-10-15 17:22 UTC
